export default [
    {"zone":"GMT-12:00","label":"International Date Line West","value":"-12"},
    {"zone":"GMT-11:00","label":"Midway Island, Samoa","value":"-11"},
    {"zone":"GMT-10:00","label":"Hawaii","value":"-10"},
    {"zone":"GMT-09:00","label":"Alaska","value":"-9"},
    {"zone":"GMT-08:00","label":"Pacific Time (US & Canada)","value":"-8"},
    {"zone":"GMT-08:00","label":"Tijuana, Baja California","value":"-8"},
    {"zone":"GMT-07:00","label":"Arizona","value":"-7"},
    {"zone":"GMT-07:00","label":"Chihuahua, La Paz, Mazatlan","value":"-7"},
    {"zone":"GMT-07:00","label":"Mountain Time (US & Canada)","value":"-7"},
    {"zone":"GMT-06:00","label":"Central America","value":"-6"},
    {"zone":"GMT-06:00","label":"Central Time (US & Canada)","value":"-6"},
    {"zone":"GMT-05:00","label":"Bogota, Lima, Quito, Rio Branco","value":"-5"},
    {"zone":"GMT-05:00","label":"Eastern Time (US & Canada)","value":"-5"},
    {"zone":"GMT-05:00","label":"Indiana (East)","value":"-5"},
    {"zone":"GMT-04:00","label":"Atlantic Time (Canada)","value":"-4"},
    {"zone":"GMT-04:00","label":"Caracas, La Paz","value":"-4"},
    {"zone":"GMT-04:00","label":"Manaus","value":"-4"},
    {"zone":"GMT-04:00","label":"Santiago","value":"-4"},
    {"zone":"GMT-03:30","label":"Newfoundland","value":"-3.5"},
    {"zone":"GMT-03:00","label":"Brasilia","value":"-3"},
    {"zone":"GMT-03:00","label":"Buenos Aires, Georgetown","value":"-3"},
    {"zone":"GMT-03:00","label":"Greenland","value":"-3"},
    {"zone":"GMT-03:00","label":"Montevideo","value":"-3"},
    {"zone":"GMT-02:00","label":"Mid-Atlantic","value":"-2"},
    {"zone":"GMT-01:00","label":"Cape Verde Is.","value":"-1"},
    {"zone":"GMT-01:00","label":"Azores","value":"-1"},
    {"zone":"GMT+00:00","label":"Casablanca, Monrovia, Reykjavik","value":"0"},
    {"zone":"GMT+00:00","label":"Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London","value":"0"},
    {"zone":"GMT+01:00","label":"Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna","value":"1"},
    {"zone":"GMT+01:00","label":"Belgrade, Bratislava, Budapest, Ljubljana, Prague","value":"1"},
    {"zone":"GMT+01:00","label":"Brussels, Copenhagen, Madrid, Paris","value":"1"},
    {"zone":"GMT+01:00","label":"Sarajevo, Skopje, Warsaw, Zagreb","value":"1"},
    {"zone":"GMT+01:00","label":"West Central Africa","value":"1"},
    {"zone":"GMT+02:00","label":"Amman","value":"2"},
    {"zone":"GMT+02:00","label":"Athens, Bucharest, Istanbul","value":"2"},
    {"zone":"GMT+02:00","label":"Beirut","value":"2"},
    {"zone":"GMT+02:00","label":"Cairo","value":"2"},
    {"zone":"GMT+02:00","label":"Harare, Pretoria","value":"2"},
    {"zone":"GMT+02:00","label":"Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius","value":"2"},
    {"zone":"GMT+02:00","label":"Jerusalem","value":"2"},
    {"zone":"GMT+02:00","label":"Minsk","value":"2"},
    {"zone":"GMT+02:00","label":"Windhoek","value":"2"},
    {"zone":"GMT+03:00","label":"Kuwait, Riyadh, Baghdad","value":"3"},
    {"zone":"GMT+03:00","label":"Moscow, St. Petersburg, Volgograd","value":"3"},
    {"zone":"GMT+03:00","label":"Nairobi","value":"3"},
    {"zone":"GMT+03:00","label":"Tbilisi","value":"3"},
    {"zone":"GMT+03:30","label":"Tehran","value":"3.5"},
    {"zone":"GMT+04:00","label":"Abu Dhabi, Muscat","value":"4"},
    {"zone":"GMT+04:00","label":"Baku","value":"4"},
    {"zone":"GMT+04:00","label":"Yerevan","value":"4"},
    {"zone":"GMT+04:30","label":"Kabul","value":"4.5"},
    {"zone":"GMT+05:00","label":"Yekaterinburg","value":"5"},
    {"zone":"GMT+05:00","label":"Islamabad, Karachi, Tashkent","value":"5"},
    {"zone":"GMT+05:30","label":"Sri Jayawardenapura","value":"5.5"},
    {"zone":"GMT+05:30","label":"Chennai, Kolkata, Mumbai, New Delhi","value":"5.5"},
    {"zone":"GMT+05:45","label":"Kathmandu","value":"5.75"},
    {"zone":"GMT+06:00","label":"Almaty, Novosibirsk","value":"6"},{"label":"(GMT+06:00) Astana, Dhaka","value":"6"},
    {"zone":"GMT+06:30","label":"Yangon (Rangoon)","value":"6.5"},
    {"zone":"GMT+07:00","label":"Bangkok, Hanoi, Jakarta","value":"7"},
    {"zone":"GMT+07:00","label":"Krasnoyarsk","value":"7"},
    {"zone":"GMT+08:00","label":"Beijing, Chongqing, Hong Kong, Urumqi","value":"8"},
    {"zone":"GMT+08:00","label":"Kuala Lumpur, Singapore","value":"8"},
    {"zone":"GMT+08:00","label":"Irkutsk, Ulaan Bataar","value":"8"},
    {"zone":"GMT+08:00","label":"Perth","value":"8"},
    {"zone":"GMT+08:00","label":"Taipei","value":"8"},
    {"zone":"GMT+09:00","label":"Osaka, Sapporo, Tokyo","value":"9"},
    {"zone":"GMT+09:00","label":"Seoul","value":"9"},
    {"zone":"GMT+09:00","label":"Yakutsk","value":"9"},
    {"zone":"GMT+09:30","label":"Adelaide","value":"9.5"},
    {"zone":"GMT+09:30","label":"Darwin","value":"9.5"},
    {"zone":"GMT+10:00","label":"Brisbane","value":"10"},
    {"zone":"GMT+10:00","label":"Canberra, Melbourne, Sydney","value":"10"},
    {"zone":"GMT+10:00","label":"Hobart","value":"10"},
    {"zone":"GMT+10:00","label":"Guam, Port Moresby","value":"10"},
    {"zone":"GMT+10:00","label":"Vladivostok","value":"10"},
    {"zone":"GMT+11:00","label":"Magadan, Solomon Is., New Caledonia","value":"11"},
    {"zone":"GMT+12:00","label":"Auckland, Wellington","value":"12"},
    {"zone":"GMT+12:00","label":"Fiji, Kamchatka, Marshall Is.","value":"12"},
    {"zone":"GMT+13:00","label":"Nuku'alofa","value":"13"}
]